### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by ninjamar** [Quantum-Codes/ScraGet#14]
Since you added docstrings, how about you add type annotations

https://towardsdatascience.com/type-annotations-in-python-d90990b172dc
https://dev.to/dstarner/using-pythons-type-annotations-4cfe
https://github.com/ninjamar/pyaw/blob/main/pyaw/core.py#L19 
https://stackoverflow.com/questions/38727520/how-do-i-add-default-parameters-to-functions-when-using-type-hinting

**Comment by Quantum-Codes** [comment]
Seems good! I'll add this in the future!

**Comment by ninjamar** [comment]
Thanks

**Comment by Quantum-Codes** [comment]
Just... replit doesn't recognize "NoReturn" lol

**Comment by ninjamar** [comment]
wdym? noreturn isn't defined. i think you mean `None`

**Comment by Quantum-Codes** [comment]
> wdym? noreturn isn't defined. i think you mean `None`

https://stackoverflow.com/a/48038206
Here.
If I make a function: ```py
def func():
#return is never used...
    print("okay...")
```
It never returns anything in whatever case. So NoReturn should be used according to the answer

**Comment by ninjamar** [comment]
> > wdym? noreturn isn't defined. i think you mean `None`
> 
> https://stackoverflow.com/a/48038206 Here. If I make a function:
> 
> ```python
> def func():
> #return is never used...
>     print("okay...")
> ```
> 
> It never returns anything in whatever case. So NoReturn should be used according to the answer

`from typing import NoReturn`

**Comment by Quantum-Codes** [comment]
I https://pypi.org/project/typing/

> For package maintainers, it is preferred to use typing;python_version<"3.5"

I don't really wanna do that

**Comment by ninjamar** [comment]
> In https://pypi.org/project/typing/
> 
> > For package maintainers, it is preferred to use typing;python_version<"3.5"
> 
> I don't really wanna do that

then don't support versions less than 3.5. python 3.5 is oldish

**Comment by Quantum-Codes** [comment]
> > In https://pypi.org/project/typing/
> > > For package maintainers, it is preferred to use typing;python_version<"3.5"
> > 
> > 
> > I don't really wanna do that
> 
> then don't support versions less than 3.5. python 3.5 is oldish

Oh, so my package will be fine if everyone uses python > 3.6?

**Comment by ninjamar** [comment]
> > > In https://pypi.org/project/typing/
> > > > For package maintainers, it is preferred to use typing;python_version<"3.5"
> > > 
> > > 
> > > I don't really wanna do that
> > 
> > 
> > then don't support versions less than 3.5. python 3.5 is oldish
> 
> Oh, so my package will be fine if everyone uses python > 3.6? Thanks!

3.6+ will work. i think your code only needs requests which needs 3.6. typing needs 3.5. i personally just choose 3.7 when i don't know because it isn't too old but it isn't super new.

**Comment by Quantum-Codes** [comment]
I'd just use None lol

**Comment by ninjamar** [comment]
I agree

**Comment by Quantum-Codes** [comment]
Ok, so I tried. https://github.com/Quantum-Codes/ScraGet/blob/0d9c0b3436826a7b2732df58cfc2972767872c3d/ScraGet/user.py#L42  
In v0.1.7 I added it. But it does nothing...

**Comment by ninjamar** [comment]
> Ok, so I tried.
> 
> https://github.com/Quantum-Codes/ScraGet/blob/0d9c0b3436826a7b2732df58cfc2972767872c3d/ScraGet/user.py#L42
> 
> 
> In v0.1.7 I added it. But it does nothing...
> I just requested for user 100 like this
> 
> ```python
> user = ScraGet.get_user()
> user.updateScratch(100) #in int format
> ```
> 
> No error was thrown :/ Unlike docstrings, replit also didn't say that str is supposed to be used.

type **hints**. it doesn't change how to code is run but it provides help to a user using ScraGet .

**Comment by Quantum-Codes** [comment]
> > Ok, so I tried.
> > https://github.com/Quantum-Codes/ScraGet/blob/0d9c0b3436826a7b2732df58cfc2972767872c3d/ScraGet/user.py#L42
> > 
> > In v0.1.7 I added it. But it does nothing...
> > I just requested for user 100 like this
> > ```python
> > user = ScraGet.get_user()
> > user.updateScratch(100) #in int format
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No error was thrown :/ Unlike docstrings, replit also didn't say that str is supposed to be used.
> 
> type **hints**. it doesn't change how to code is run but it provides help to a user using ScraGet.

Can you give an example? I expected a popup like docstr

**Comment by ninjamar** [comment]
> Can you give an example? I expected a popup like docstr
Ide's like replit show the docstring and the function definition (` def updateScratch(self, user: str) -> None: `) so when the user writes code, they know what type of argument to pass in. This also helps with documentation generators. 
https://stavshamir.github.io/python/the-other-benefit-of-python-type-annotations/

**Comment by Quantum-Codes** [comment]
Oh thanks!!! I get it! I saw it in the pop-up too lol!

Well, the union operator doesn't work.
```python
def hello(text : int | str) #unsupported operator | for type and type
  print(text)
.```
Couldn't find info on google

**Comment by ninjamar** [comment]
not sure

**Comment by Quantum-Codes** [comment]
Maybe an issue with annotations? Anyways I completed this except for that..

**Comment by ninjamar** [comment]
[Sure](https://stackoverflow.com/questions/33945261/how-to-specify-multiple-return-types-using-type-hints)

**Comment by Quantum-Codes** [comment]
> https://stackoverflow.com/questions/33945261/how-to-specify-multiple-return-types-using-type-hints

You mean replit isn't using py 3.10?

**Comment by ninjamar** [comment]
replit python doesn't use 3.10 but u can use a nix replit and in the dependencies put python3.10
